#!/bin/env bash
echo "copying content..."
cp -R ${OPENSHIFT_REPO_DIR}www/_content ${OPENSHIFT_DATA_DIR}content_temp
rm -f ${OPENSHIFT_DATA_DIR}content_bkp.tgz
tar czf ${OPENSHIFT_DATA_DIR}content_bkp.tgz ${OPENSHIFT_DATA_DIR}content
rm -rf ${OPENSHIFT_DATA_DIR}content
mv ${OPENSHIFT_DATA_DIR}content_temp ${OPENSHIFT_DATA_DIR}content
